name: pom.xml version determine
on:
  push:
    branches:
      - main

jobs:
  pom-finds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Perform REST API request
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          ORG_NAME="lokeshorg"
          
          REPOS_URL="https://api.github.com/orgs/${ORG_NAME}/repos"
          REPO_RESPONSE=$(curl -s -H "Authorization: Bearer $BEARER_TOKEN" "$REPOS_URL")
          echo "Repository response: $REPO_RESPONSE"